# Preprocessing Text For Word Embeddings

In [ ]:
import pandas as pd

# Bert imported necessary libraries
import random
import torch
from transformers import BertTokenizer, BertModel
from sklearn.metrics.pairwise import cosine_similarity

# !pip install fasttext
# import fasttext

# import fasttext.util
# fasttext.util.download_model('en', if_exists='ignore')  # English
# ft = fasttext.load_model('cc.en.300.bin')

training = pd.read_csv("sent_train.csv")

KeyboardInterrupt:

In [ ]:
# Set a random seed
random_seed = 42
random.seed(random_seed)

# Set a random seed for PyTorch (for GPU as well)
torch.manual_seed(random_seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(random_seed)

In [ ]:
# Load BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
from google.colab import files
#files.upload()

!pip install emoji nltk

import re, emoji, nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

valid = pd.read_csv("sent_valid.csv")
print("Columns:", training.columns.tolist())

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 10.8 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0
Train shape: (9543, 2)  Valid shape: (2388, 2)
Columns: ['text', 'label']

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
display(training.head(5))

                                                text  label
0  $BYND - JPMorgan reels in expectations on Beyo...      0
1  $CCL $RCL - Nomura points to bookings weakness...      0
2  $CX - Cemex cut at Credit Suisse, J.P. Morgan ...      0
3  $ESS: BTIG Research cuts to Neutral https://t....      0
4  $FNKO - Funko slides after Piper Jaffray PT cu...      0

In [ ]:

# Load the dataset
training = pd.read_csv("/content/sent_train.csv")
valid = pd.read_csv("/content/sent_valid.csv")

Shape: (9543, 2)

Column names: Index(['text', 'label'], dtype='object')

Missing values:
 text     0
label    0
dtype: int64

Label distribution:
label
2    6178
1    1923
0    1442
Name: count, dtype: int64

# Cleaning and Normalizing

In [ ]:
import pandas as pd
import re
import emoji
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

# Base stopwords list
stop_words = set(stopwords.words('english'))

# Keep key words needed for meaning
keep_words = {'and', 'but', 'or', 'is', 'are', 'was', 'were', 'should', 'would', 'could',
              'a', 'an', 'the', 'in', 'on', 'at', 'with', 'for', 'of', 'after', 'before', 'by', 'as'}

smart_stopwords = stop_words - keep_words

#for financial terms
custom_removals = {'via', 'eps', 'bln', 'ipo', 'fomc', 'mclr', 'usmca', 'nyse',
                   'gapping', 'afterhours', 'premarket', 'today', 'week', 'month',
                   'years', 'days', 'time', 'billion', 'million', 'trillion', 'say'}
# Hi guys, here are some other low-value words we could possibly add
# {'ppi', 'nse', 'reports', 'results', 'started', 'buy', 'target', 'looking', 'proud', 'vies',
#  'title', 'halts', 'mainland', 'little', 'bit', 'percent', 'should', 'concerned', 'historical',
#  'volatility', 'audited', 'company', 'health', 'stock', 'transaction', 'project', 'program',
#  'update', 'announcement', 'facility', 'otm', 'reit', 'big', 'winners', 'loan', 'ratio', 'good'}


def smart_clean_text(text):
    text = str(text)

    text = re.sub(r'\.\.\.|\…|more:', ' ', text)

    text = emoji.replace_emoji(text, replace='')
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#\w+', '', text)
    text = re.sub(r'\$\w+', '', text)
    text = re.sub(r'\b[A-Z]{2,5}:[A-Z]{1,5}\b', '', text)
    text = re.sub(r'\([A-Z]{1,5}\)', '', text)
    text = re.sub(r'\b[A-Z]{2,5}/[A-Z]{2,5}\b', '', text)

    text = re.sub(r'[^\w\s]', ' ', text)
    text = re.sub(r'\d+(\.\d+)?%?', '', text)

    text = text.lower()

    text = ' '.join([word for word in text.split() if word not in smart_stopwords])

    text = ' '.join([word for word in text.split() if len(word) > 2])

    text = re.sub(r'\s+', ' ', text).strip()
    return text

# add a column that has the cleaned text to training and valid csv
training['clean_text'] = training['text'].astype(str).apply(smart_clean_text)
valid['clean_text'] = valid['text'].astype(str).apply(smart_clean_text)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

label
2    0.647386
1    0.201509
0    0.151106
Name: proportion, dtype: float64

In [ ]:
valid = pd.read_csv("sent_valid.csv")

# Apply the same text cleaning function
valid['clean_text'] = valid['text'].astype(str).apply(smart_clean_text)

import nltk
from nltk import word_tokenize, pos_tag

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

def extract_features(text):
    words = word_tokenize(text)
    tagged = pos_tag(words)

    nouns = sum(1 for word, tag in tagged if tag.startswith('NN'))
    adjectives = sum(1 for word, tag in tagged if tag.startswith('JJ'))
    verbs = sum(1 for word, tag in tagged if tag.startswith('VB'))
    word_count = len(words)

    return pd.Series([nouns, adjectives, verbs, word_count])

training[['nouns', 'adjectives', 'verbs', 'word_count']] = training['clean_text'].apply(extract_features)
valid[['nouns', 'adjectives', 'verbs', 'word_count']] = valid['clean_text'].apply(extract_features)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

# Download Cleaned Datasets

In [ ]:
# training.to_csv('training_cleaned.csv', index=False)
# valid.to_csv('valid_cleaned.csv', index=False)

# from google.colab import files
# files.download('training_cleaned.csv')
# files.download('valid_cleaned.csv')

# **Generate Embeddings Using BERT (0.1B Parameters)**

In [ ]:
import pandas as pd
training_embed = pd.read_csv("training_embed.csv")

In [ ]:
training_embed["label"].value_counts()

label
2    6178
1    1923
0    1442
Name: count, dtype: int64

In [ ]:
print(training_embed.bert_embedding.sample(1))

8924    [ 3.27210426e-01 -4.59803849e-01  3.61305505e-...
Name: bert_embedding, dtype: object

In [ ]:
training_embed.sample(3)

,text,label,clean_text,nouns,adjectives,verbs,word_count,bert_embedding,financialBERT_embedding,llama_embedding
8453,Did Changing Sentiment Drive MDxHealth's (EBR:...,2,changing sentiment drive mdxhealth share price...,6,0,1,7,[ 2.41747379e-01 -3.22208315e-01 4.23823118e-...,[ 9.39361081e-02 -1.08240497e+00 -6.12033427e-...,"[0.007686462718993425, -0.007204249035567045, ..."
5714,VC Deals: AbbVie Joins $50M For Inflammatory D...,2,deals abbvie joins for inflammatory disease tr...,4,1,1,7,[ 6.08682074e-02 4.61948477e-03 3.86340022e-...,[ 1.46445602e-01 -4.96248662e-01 -3.15353811e-...,"[-0.03644357994198799, -0.0423160158097744, -0..."
9380,Nokia and Ericsson both advance after Barr say...,1,nokia and ericsson advance after barr says fir...,6,0,2,11,[ 2.18330517e-01 3.80555391e-02 9.07392055e-...,[-3.41635034e-03 -3.44432384e-01 -3.83144587e-...,"[-0.013515187427401543, 0.019398551434278488, ..."

In [ ]:
for n in training_embed["clean_text"]:
  print(n)

jpmorgan reels expectations beyond meat
nomura points bookings weakness carnival and royal caribbean
cemex cut credit suisse morgan weak building outlook
btig research cuts neutral
funko slides after piper jaffray cut
technipfmc downgraded berenberg but called top pick deutsche bank
loses bull
deutsche bank cuts hold
cowen cuts market perform
trendforce cuts iphone estimate after foxconn delay
moody warns harley davidson
citing aero ties wells slashes hexcel
intelsat cut market perform raymond james
compass point cuts sell
muddy waters goes short luckin coffee
mantech downgraded ahead difficult comps
oppenheimer cuts perform
mplx cut credit suisse potential dilution marathon strategic review
imperial downgrades msg networks amid sports free airwaves
piper hits the materialise sidelines
hovde group cuts market perform
new netflix bear steps
shopify loses bull
nomura instinet loses confidence extended stay america
twilio gets street low target virus risk
guggenheim minerd sees gloom ahead stocks
moffettnathanson expects nfl costs skyrocket
barrington research cuts mkt perform
mizuho cuts xlnx target near term headwinds
downgraded sector weight overweight keybanc capital
alphabet and facebook price targets cut barclays weaker outlook
amc networks price target cut imperial capital
american software downgraded neutral buy riley fbr
analysts question silicon motion margin outlook
anchiano therapeutics downgraded peer perform outperform oppenheimer
arch coal stock price target cut riley fbr
downgraded moffettnathanson sell concern wireless carry the whole company
shares sink after moffettnathanson downgrade
stock falls after moffettnathanson downgrades saying dividend looks less compelling
aurora cannabis stock price target cut stifel nicolaus
autodesk downgraded underweight neutral jpmorgan
baml warns profit pressure for hormel
barclays cools molson coors
becton dickinson downgraded outperform strong buy raymond james
becton dickinson downgraded sector weight overweight keybanc capital
berry petroleum downgraded market perform outperform bmo capital
berry petroleum downgraded underweight sector weight keybanc capital
bluebird bio downgraded line outperform evercore isi
bluebird bio stock price target cut evercore isi
canada goose downgraded buy strong buy cfra
canada goose stock price target cut cfra
children place downgraded commerce puts margins risk
children place price target cut monness crespi hardt
cinedigm corp analysts are cutting estimates need know
clovis oncology stock price target cut evercore isi
cumberland pharmaceuticals stock price target cut riley fbr
dell hpe targets trimmed compute headwinds
dish may key winner amid intelsat woes analyst
disney downgraded analyst says parks attendance could take years normalize
downgrades
downgrades
dropbox watch after stinging spruce point report
earnings update electrocore inc reported and analysts are trimming forecasts
evercore downgrades bluebird bio and clovis premarket analyst action
fannie mae freddie mac downgraded sell analyst cites unintended consequences cares act
forescout downgraded neutral buy monness crespi hardt
formfactor cut unsustainable revenue outlook
funko downgraded hold buy stifel nicolaus
funko stock price target cut stifel nicolaus
stock price target cut deutsche bank
grubhub gains bear margin view
downgraded argus drilling industry weakness seen persisting
hanesbrands stock price target cut bofa merrill lynch
helmerich payne started sell with stock price target deutsche bank
hexo stock price target cut mkm partners
home depot stock price target cut instinet
intelsat downgraded underweight neutral morgan
intelsat lower after morgan stanley target cut
jefferies warns brands
kohl stock price target cut deutsche bank
kohl stock price target cut wedbush
brands stock price target cut wedbush
lovesac stock price target cut canaccord
lyft stock price target cut deutsche bank
macerich downgraded underweight sector weight keybanc capital
marinus pharma stock price target cut leerink
methanex downgraded securities valuation
metro inc missed earnings and eps looked sad but analysts updated models
mid america apartment communities downgraded sector weight overweight keybanc capital
mitek systems stock price target cut benchmark
napco security stock price target cut imperial capital
needham martin defends prediction netflix subscriptions fall
netflix downgraded underperform needham
netflix stock falls after wells fargo turns bearish
new netflix bear steps
new york opioid case significant risk for pharma stocks says bearish bofa
norwegian cruise line downgraded strong sell hold cfra
novo nordisk downgraded ubs concerns drug launch cost
oppenheimer cuts estimates yum china
orbcomm price target lowered canaccord
reilly automotive stock price target cut morgan
patterson uti energy started sell with stock price target deutsche bank
business parks downgraded underweight sector weight keybanc capital
rio tinto downgraded neutral overweight morgan
rosenblatt projects downside apple shares warns drop iphone production
royal caribbean downgraded sell buy cfra
royal caribbean stock price target cut cfra
royal caribbean stock falls after cfra swings bearish dire coronavirus assessment
scandinavian tobacco group earnings missed analyst estimates analysts are forecasting
sherwin williams cut conviction buy goldman valuation
sirius downgraded valuation
spotify double downgrade reflects prospect slower revenue growth
suntrust latest trim nielsen target
taco bell parent yum brands downgraded neutral buy btig
take two downgraded murky game slate
take two interactive stock price target cut mkm partners
target hospitality downgraded perform outperform oppenheimer
taubman centers downgraded sector weight overweight keybanc capital
the manitowoc company inc reported earnings and analysts cut target price
transocean started sell with stock price target deutsche bank
ultra clean downgraded hold buy stifel nicolaus
wells fargo downgrades netflix underperform but sees takeover target nflx could get acquired nflx
wells fargo downgrades netflix spending concerns
wells fargo downgrades netflix content king cash queen
welltower stock price target cut morgan
wwe stock price target cut benchmark
dougherty company starts buy
amd navi shows strong adoption bofa
bmo capital markets ups outperform
lake street starts buy
raises centene corp rtg bbb outlk stable
citi gives big boost deere
guggenheim sees favorable catalysts for ebay
freeport upgraded credit suisse sees big buying opportunity
btig research starts buy
franco nevada need funding despite suspensions analyst says
cantor fitzgerald resumes overweight
morgan stanley sees doubling bull case scenario
barclays starts overweight
hasbro gains after ubs upgrade
new bull praises acceleration margin profile
barclays ups overweight
jpmorgan constructive kraft heinz
compass point ups neutral
lowe racks another positive rating despite recession risk
lam target boosted compelling setup
barclays starts overweight
bull sees upsides for wdc
rated buy
suntrust expecting netflix post strong user growth
nvidia set for gaming tailwinds bofa
btig sees material improvement ocwen book value
cowen starts outperform
bmo capital markets starts outperform
evercore starts ringcentral outperform
moffettnathanson boosts sbac buy
loop turns bullish snap growth
lake street starts buy
cowen sees upside tenb indegy purchase
uber lyft raise prices profit barclays
maxim group ups buy
compass point ups buy
new zscaler bull sees sustainable growth shares
activision take two charts look constructive wells fargo gets bullish video game plays trader
adobe stock price target raised wedbush
adobe stock price target raised instinet
aegis capital positive netflix usage trend
after drop months bank america says buy pot stock canopy
akero therapeutics started buy with stock price target canaccord genuity
align technology stock price target raised stifel nicolaus
allergan upgraded buy neutral ubs
altria stock price target raised stifel nicolaus
amneal pharma price target raised suntrust robinson humphrey
analyst loop capital upgrades buy hold citing higher revenue growth potential
analyst the top telecom pick for
analysts mostly bullish newly public insurance firm brp group
analysts see gains ahead for the holdings the first trust dow jones internet index fund etf
ansys stock price target raised benchmark
anthem stock price target raised suntrust
applied industrial technologies stock price target raised keybanc capital
argen stock price target raised instinet
armata pharmaceuticals started buy with stock price target maxim group
arrow electronics stock price target raised suntrust robinson humphrey
asset management one bullish call treasuries one for the long long run
audentes therapeutics stock price target raised evercore isi
audentes therapeutics upgraded outperform line evercore isi
axcelis technologies stock price target raised benchmark
baird bullish beat canada goose
baird likes drug wholesalers premarket analyst action
baird returns wingstop bull camp
baker hughes started buy with stock price target deutsche bank
bank america stock price target raised oppenheimer
barclays analysts says uber and lyft are well positioned achieve profitability
bausch health upgraded overweight neutral jpmorgan price target raised
bed bath beyond reiterated buy bofa merrill lynch
belden stock price target raised suntrust robinson humphrey
benchmark says roof supplier buy
bernstein turns bullish vmware valuation
berry petroleum upgraded sector weight underweight keybanc capital
best buy stock price target raised oppenheimer
biogen stock price target raised instinet
biogen stock price target raised svb leerink
boeing stock price target raised cfra
bofa upgrades westrock after containerboard conference london pulp week
bouygues beat analyst forecasts and analysts updating predictions
btig expects domino boost buybacks
btig sees material improvement ocwen book value
bull sees upsides for wdc
cabot upgraded buy neutral ubs
canada goose upgraded outperform neutral baird price target
capital southwest initiated outperform raymond james with price target
celanese stock price target raised bofa merrill lynch
industries stock price target raised bofa merrill lynch
industries upgraded buy neutral bofa merrill lynch
ciena stock price target raised instinet
citi gives big boost deere
citi reels skin
citron says long luckin coffee citron
cnh industrial upped buy deutsche bank valuation
copa holdings stock price target raised deutsche bank
costco price target raised bofa merrill lynch
csx stock price target raised deutsche bank
csx upgraded buy hold deutsche bank
cvs health stock price target raised suntrust
cyrusone upgraded overweight sector weight keybanc capital
diamondrock hospitality upgraded sector weight underweight keybanc capital
dlh holdings maintained buy with price target canaccord
domtar upgraded market perform bmo capital
dow stock price target raised bofa merrill lynch
earnings update analysts lifted aemetis inc price target
earnings update analysts lifted milestone scientific inc price target
earnings update analysts lifted skyworks solutions inc price target
eastman chemical stock price target raised bofa merrill lynch
edgewell stock price target raised cfra
elastic upgraded buy hold canaccord genuity
enbridge upgraded buy neutral ubs price target lifted
energizer holdings upgraded neutral underweight morgan price target lifted
energizer shakes jpmorgan bear call
equity lifestyle properties upgraded outperform bmo capital
estee lauder stock price target raised raymond james
etsy initiated buy with price target suntrust robinson humphrey
fedex stock price target raised bofa securities
fleetcor stock price target raised cfra
ford electric suv impresses credit suisse
fortinet stock price target raised bmo capital
fortinet stock price target raised monness crespi hardt
glenmark pharmaceuticals limited beat analyst forecasts and analysts updating predictions
goldman adds workday conviction list shares
goldman says rally brazilian retailer room run
grubhub stock price target raised oppenheimer
grubhub stock price target raised susquehanna
hasbro upgraded earnings growth potential entertainment one acquisition
hasbro upgraded buy neutral ubs price target
heat biologics started buy with stock price target maxim group
home depot upgraded outperform neutral credit suisse price target raised
humana stock price target raised deutsche bank
huntsman named conviction buy goldman chemical sector shuffle
intel stock price target raised suntrust robinson humphrey
intercept pharmaceuticals maintained buy with price target canaccord
invitae corp maintained buy benchmark
penney stock price target raised cents riley fbr
jabil stock price target raised cfra
jefferies analysts lifted tesla shares buy paring the price target
jpmorgan likes bausch health premarket analyst action
jpmorgan bullish uber upside potential
kilroy realty upgraded overweight sector weight keybanc capital
lharris started buy with stock price target benchmark
lagging mlp upgraded goldman new projects seen lifting cash flows
ligand pharmaceuticals started buy with stock price target benchmark
lovesac maintained buy canaccord
lululemon stock price target raised susquehanna
lyft stock gets upgrade due competitive positioning
lyondellbasell sock price target raised bofa merrill lynch
magnolia oil gas started overweight with stock price target keybanc capital
mesa air reiterated outperform cowen
microchip technology stock price target raised suntrust robinson humphrey
mizuho raises intel aggressive price cuts
molina healthcare stock price target raised suntrust
morgan stanley analyst joseph moore upgraded nvidia nasdaq equalweight overweight with price tar
morgan stanley bullish eldorado resorts ahead caesars combination
morgan stanley joins mortgage sector bulls
morgan stanley raises fortinet price target after bullish analyst day
morgan stanley upgrades nvidia equal weight overweight and announces price target
morgan stanley upgrades nvidia buy predicting return solid growth
munster doubles says apple upside year
new bull sees upside for splunk
new for subscribers morgan stanley adds amazon list favorite stocks are the rest
newmont goldcorp stock price target raised riley fbr
nlight target raised nutronics deal
nokia stock price target raised mkm partners
nuvasive upgraded outperform market perform leerink
nvidia one the best opportunities maintain high multiple morgan stanley says upgrade
nvidia stock climbs after morgan stanley turns bullish
nxp semiconductors stock price target raised suntrust robinson humphrey
olin corp stock price target raised bofa merrill lynch
one analyst says could unlock significant value selling minority stake ameritrade after purchase
onto innovation stock price target raised benchmark
owens corning upgraded wells after raising residential insulation prices
owens corning upgraded strong insulation roofing potential
oyster point pharma initiated overweight with price target morgan
paul tudor jones sees the potential for stock market explosion the upside
pennmac financial rises record piper gets bullish
piper likes dexcom premarket analyst action
pixelworks inc reported and analysts lifting price targets
ppg industries stock price target raised bofa merrill lynch
prothena upgraded outperform line evercore isi
purple innovation initiated overweight with price target keybanc capital
quanterix maintained outperform with price target leerink
results kla corporation beat earnings expectations and analysts new forecasts
rpm international stock price target raised bofa merrill lynch
global stock price target raised stifel nicolaus
sanderson farms stock price target raised morgan
schlumberger started buy with stock price target deutsche bank
selvaag bolig asa beat earnings expectations analysts think happen next
softbank the last laugh with wework deal one bernstein analyst says
sonoma pharma maintained buy with price target benchmark
splunk upgraded overweight morgan stanley
starbucks stock buy according investment bank
starbucks upgraded overweight morgan after meeting with executives
stifel upgrades parker hannifin potential synergies industry recovery prospects
stifel upgrades wendy bullish breakfast and digital prospects
syanptics raised forecast margin strength
synaptics stock price target raised morgan
synopsys upgraded overweight neutral jpmorgan price target raised
connectivity stock price target raised suntrust robinson humphrey
teekay tankers upped two notches buy baml
texas instruments stock price target raised suntrust robinson humphrey
twitter stock price target raised wedbush
twitter stock price target raised suntrust
twitter stock price target raised susquehanna
twitter inc reported and analysts lifting price targets
well services initiated buy with price target stifel
uber stock price target raised mkm partners
uber stock price target raised bofa securities
uber stock price target raised oppenheimer
uber stock price target raised wedbush
uber stock price target raised deutsche bank
ubs raises peloton price target
ubs upgrades hasbro strong sales frozen dolls black friday
udr upgraded overweight sector weight keybanc capital
unisys stock price target raised sidoti
unitedhealth stock price target raised cfra
upgrades
upgrades
vertex pharmaceuticals stock price target raised bmo capital
vertical research expects allison transmission break
voyager therapeutics started outperform with stock price target oppenheimer
walt disney stock price target raised imperial capital
wells fargo analyst dori kesten lifted rating marriott overweight noting the hotel chain sha
wells still bullish mobile after unsurprising ceo change
westlake chemical stock price target raised bofa merrill lynch
westrock stock price target raised bofa merrill lynch
westrock upgraded buy neutral bofa merrill lynch
credit suisse sees the gaining
williams cos initiated buy with price target suntrust robinson humphrey
workday added goldman conviction list stock gains
zendesk stock price target raised stifel nicolaus
zendesk targets raised after solid results
mkm partners puts number victoria secret
baird returns wingstop bull camp
analysts react fcc decision intelsat band spectrum auction
arex capital ramps pressure zagg
aviation capital group assigned baa rating moody
benzinga top upgrades downgrades for december
benzinga top upgrades downgrades for november
brp group started hold with stock price target jefferies
btig resumes coverage range healthcare stocks neutral abbvie
bull camp empty sally beauty
analysts think vecima networks inc worth after results
chicken soup for the soul entertainment inc third quarter results analysts are forecasting for next year
citron research owned the prominent short seller andrew left placed price target
coin toss morgan stanley raises tesla bull case keeps bear case
gds holdings limited released third quarter earnings analysts think
global automotive tensioner market growing adoption start stop system boost growth technavio
are the biggest analyst calls the day johnson johnson canopy growth intelsat
are the biggest analyst calls the day netflix nvidia lyft molson coors snap
are the biggest analyst calls the day netflix nvidia lyft molson coors snap
inc initiated neutral susquehanna
liveperson started neutral with stock price target morgan
miller value partners likes two stocks bearish one
mkm partners puts number victoria secret
morgan stanley new favorite pick the chip space
mplx initiated hold with price target suntrust robinson humphrey
oppenheimer calls transformation big box retailer
pipestone energy corp reported and analysts assigned price target
royal caribbean cruises ltd full year results came analysts are forecasting for next year
spirit airlines inc released full year results and analysts are updating estimates
stock market update nvidia shares upgraded netflix downgraded
tjx factset consensus cents

In [ ]:
# BERT Embedding Function
def get_bert_embedding(text):
  # Tokenizes and encodes text
  inputs = tokenizer(text, # Input text
                     padding = True, # Ensures all sequences in a batch are padded to the same length
                     truncation = True, # Enables truncation for sequences that exceed a specified max length
                     return_tensors = 'pt', # Format of returned tensors in PyTorch should be torch.Tensor objects (required for pyTorch)
                     add_special_tokens = True # Adds specialized tokens such as CLS, SEP, and PAD
                     )

  # CLS is placed at the beginning to capture overall meaning via aggregation
  # SEP is used to separate two different sentences or to mark the end of a sentence
  # PAD is added to shorter sentences to match the length of the longer sentences

  # Generates embeddings using BERT
  with torch.no_grad():
    outputs = model(**inputs)

  # outputs.last_hidden_state (batch size, sequence_length, hidden_size)
  # batch_size: Amount of sentences fed into the model
  # sequence_length: How many tokens are in each sentence
  # hidden_size: Dimensionality of each token embedding (768 features)
  token_embeddings = outputs.last_hidden_state

  # Compute the average of all token embeddings to get a sentence level vector per sentence rather than per token
  mean_pooled = token_embeddings.mean(dim=1)
  return mean_pooled.squeeze().numpy()

In [ ]:
# Apply the embedding function row by row
training['embedding'] = training['clean_text'].apply(get_bert_embedding)

In [ ]:
training.head(20)

,text,label,clean_text,nouns,adjectives,verbs,word_count,embedding
0,$BYND - JPMorgan reels in expectations on Beyo...,0,jpmorgan reels expectations beyond meat,4,0,0,5,"[0.04343193, -0.17159984, -0.006442541, -0.012..."
1,$CCL $RCL - Nomura points to bookings weakness...,0,nomura points bookings weakness carnival and r...,6,1,0,8,"[-0.3959833, -0.30719957, 0.0661829, 0.0602318..."
2,"$CX - Cemex cut at Credit Suisse, J.P. Morgan ...",0,cemex cut credit suisse morgan weak building o...,6,2,0,8,"[-0.13003948, -0.18834782, 0.13463801, 0.21141..."
3,$ESS: BTIG Research cuts to Neutral https://t....,0,btig research cuts neutral,2,2,0,4,"[-0.14499637, -0.09896575, -0.38878652, 0.0516..."
4,$FNKO - Funko slides after Piper Jaffray PT cu...,0,funko slides after piper jaffray cut,4,0,0,6,"[-0.09609649, -0.55792147, 0.21134444, 0.02747..."
5,$FTI - TechnipFMC downgraded at Berenberg but ...,0,technipfmc downgraded berenberg but called top...,5,1,2,9,"[-0.30310422, -0.42411697, 0.0786846, 0.188643..."
6,$GM - GM loses a bull https://t.co/tdUfG5HbXy,0,loses bull,2,0,0,2,"[-0.36897755, -0.11082789, -0.0016138963, 0.13..."
7,$GM: Deutsche Bank cuts to Hold https://t.co/7...,0,deutsche bank cuts hold,3,0,1,4,"[-0.016315749, -0.39343968, -0.30481496, 0.023..."
8,$GTT: Cowen cuts to Market Perform,0,cowen cuts market perform,4,0,0,4,"[0.09511597, -0.20545241, -0.3813022, 0.052350..."
9,$HNHAF $HNHPD $AAPL - Trendforce cuts iPhone e...,0,trendforce cuts iphone estimate after foxconn ...,5,1,0,7,"[0.18357043, -0.42415977, 0.5561008, 0.2305212..."
10,$HOG - Moody's warns on Harley-Davidson https:...,0,moody warns harley davidson,2,0,1,4,"[0.07060688, -0.05228454, -0.12458859, -0.0421..."
11,"$HXL - Citing aero ties, Wells slashes PT on H...",0,citing aero ties wells slashes hexcel,4,0,2,6,"[0.29323444, -0.07679839, 0.38283917, 0.245503..."
12,$I - Intelsat cut to Market Perform at Raymond...,0,intelsat cut market perform raymond james,4,1,1,6,"[-0.049182955, -0.10533347, 0.070768684, 0.271..."
13,$KRG: Compass Point cuts to Sell https://t.co/...,0,compass point cuts sell,3,0,1,4,"[-0.027154854, -0.17204715, -0.28879294, 0.131..."
14,$LK - Muddy Waters goes short Luckin Coffee ht...,0,muddy waters goes short luckin coffee,3,1,1,6,"[0.08503317, -0.051914103, -0.017377153, 0.009..."
15,$MANT - ManTech downgraded ahead of difficult ...,0,mantech downgraded ahead difficult comps,2,1,1,5,"[-0.519382, -0.4659775, 0.027571594, 0.3344722..."
16,$MDCO: Oppenheimer cuts to Perform,0,oppenheimer cuts perform,2,0,1,3,"[0.1500701, 0.057495028, -0.21151376, -0.21775..."
17,$MPLX $MPC - MPLX cut at Credit Suisse on pote...,0,mplx cut credit suisse potential dilution mara...,6,2,1,9,"[-0.02481054, -0.2878825, 0.060657755, 0.24560..."
18,$MSGN - Imperial downgrades MSG Networks amid ...,0,imperial downgrades msg networks amid sports f...,4,2,1,8,"[-0.3312836, 0.01721535, 0.12168377, 0.3657687..."
19,$MTLS - Piper hits the Materialise sidelines h...,0,piper hits the materialise sidelines,3,0,1,5,"[-0.095521964, -0.42321953, -0.13074943, 0.065..."

# **Rename embedding to bert_embedding and download new dataset**

In [ ]:
training.rename(columns={'embedding': 'bert_embedding'}, inplace=True)

training.to_csv('training_embed.csv', index=False)

from google.colab import files
files.download('training_embed.csv')

# **FinancialBERT (0.1B Parameters) Embedding**

In [ ]:
from transformers import BertTokenizer, BertModel

tokenizer = BertTokenizer.from_pretrained("ahmedrachid/FinancialBERT")
model     = BertModel.from_pretrained("ahmedrachid/FinancialBERT")
model.eval()
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

# Same as BERT Implementation
def get_financialbert_embedding(text):
    inputs = tokenizer(
        text,
        padding=True,
        truncation=True,
        return_tensors='pt',
        add_special_tokens=True
    )

    with torch.no_grad():
        outputs = model(**inputs)

    token_embeddings = outputs.last_hidden_state
    mean_pooled      = token_embeddings.mean(dim=1)
    return mean_pooled.squeeze().numpy()

Some weights of BertModel were not initialized from the model checkpoint at ahmedrachid/FinancialBERT and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
# Apply the embedding function row by row
training['embedding'] = training['clean_text'].apply(get_financialbert_embedding)

In [ ]:
training.rename(columns={'embedding': 'financialBERT_embedding'}, inplace=True)
training.head(20)

training.to_csv('training_embed.csv', index=False)

from google.colab import files
files.download('training_embed.csv')

# **Llama 3.1 (8B Parameters) Embedding**

In [ ]:
!pip install llama-index
!pip install llama-index-embeddings-huggingface
!pip install transformers sentence-transformers

from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings

Settings.embed_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-small-en-v1.5" # Well-performing and fast default from Hugging Face
)

Requirement already satisfied: llama-index in /usr/local/lib/python3.12/dist-packages (0.14.7)
Requirement already satisfied: llama-index-cli<0.6,>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-index) (0.5.3)
Requirement already satisfied: llama-index-core<0.15.0,>=0.14.7 in /usr/local/lib/python3.12/dist-packages (from llama-index) (0.14.7)
Requirement already satisfied: llama-index-embeddings-openai<0.6,>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-index) (0.5.1)
Requirement already satisfied: llama-index-indices-managed-llama-cloud>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from llama-index) (0.9.4)
Requirement already satisfied: llama-index-llms-openai<0.7,>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from llama-index) (0.6.7)
Requirement already satisfied: llama-index-readers-file<0.6,>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-index) (0.5.4)
Requirement already satisfied: llama-index-readers-llama-parse>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from llama-index) (0.5.1)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.12/dist-packages (from llama-index) (3.9.1)
Requirement already satisfied: aiohttp<4,>=3.8.6 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (3.13.2)
Requirement already satisfied: aiosqlite in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (0.21.0)
Requirement already satisfied: banks<3,>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (2.2.0)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (1.2.18)
Requirement already satisfied: dirtyjson<2,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (1.0.8)
Requirement already satisfied: filetype<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (1.2.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (2025.3.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (0.28.1)
Requirement already satisfied: llama-index-workflows!=2.9.0,<3,>=2 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (2.11.0)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (3.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (2.0.2)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (11.3.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (4.5.0)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (2.11.10)
Requirement already satisfied: pyyaml>=6.0.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (6.0.3)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (2.32.4)
Requirement already satisfied: setuptools>=80.9.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (80.9.0)
Requirement already satisfied: sqlalchemy>=1.4.49 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15.0,>=0.14.7->llama-index) (2.0.44)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (8.5.0)
Requirement already satisfied: tiktoken>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (0.12.0)
Requirement already satisfied: tqdm<5,>=4.66.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (4.67.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (4.15.0)
Requirement already satisfied: typing-inspect>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (0.9.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.7->llama-index) (1.17.3)
Requirement already satisfied: openai>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-embeddings-openai<0.6,>=0.5.0->llama-index) (1.109.1)
Requirement already satisfied: llama-cloud==0.1.35 in /usr/local/lib/python3.12/dist-packages (from llama-index-indices-managed-llama-cloud>=0.4.0->llama-index) (0.1.35)
Requirement already satisfied: certifi>=2024.7.4 in /usr/local/lib/python3.12/dist-packages (from llama-cloud==0.1.35->llama-index-indices-managed-llama-cloud>=0.4.0->llama-index) (2025.10.5)
Requirement already satisfied: beautifulsoup4<5,>=4.12.3 in /usr/local/lib/python3.12/dist-packages (from llama-index-readers-file<0.6,>=0.5.0->llama-index) (4.13.5)
Requirement already satisfied: defusedxml>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-readers-file<0.6,>=0.5.0->llama-index) (0.7.1)
Requirement already satisfied: pandas<2.3.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-readers-file<0.6,>=0.5.0->llama-index) (2.2.2)
Requirement already satisfied: pypdf<7,>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-readers-file<0.6,>=0.5.0->llama-index) (6.1.3)
Requirement already satisfied: striprtf<0.0.27,>=0.0.26 in /usr/local/lib/python3.12/dist-packages (from llama-index-readers-file<0.6,>=0.5.0->llama-index) (0.0.26)
Requirement already satisfied: llama-parse>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-readers-llama-parse>=0.4.0->llama-index) (0.6.54)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>3.8.1->llama-index) (8.3.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>3.8.1->llama-index) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>3.8.1->llama-index) (2024.11.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.7->llama-index) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.7->llama-index) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.7->llama-index) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.7->llama-index) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.7->llama-index) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.7->llama-index) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.7->llama-index) (1.22.0)
Requirement already satisfied: griffe in /usr/local/lib/python3.12/dist-packages (from banks<3,>=2.2.0->llama-index-core<0.15.0,>=0.14.7->llama-index) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from banks<3,>=2.2.0->llama-index-core<0.15.0,>=0.14.7->llama-index) (3.1.6)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5,>=4.12.3->llama-index-readers-file<0.6,>=0.5.0->llama-index) (2.8)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx->llama-index-core<0.15.0,>=0.14.7->llama-index) (4.11.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx->llama-index-core<0.15.0,>=0.14.7->llama-index) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx->llama-index-core<0.15.0,>=0.14.7->llama-index) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx->llama-index-core<0.15.0,>=0.14.7->llama-index) (0.16.0)
Requirement already satisfied: llama-index-instrumentation>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-workflows!=2.9.0,<3,>=2->llama-index-core<0.15.0,>=0.14.7->llama-index) (0.4.2)
Requirement already satisfied: llama-cloud-services>=0.6.54 in /usr/local/lib/python3.12/dist-packages (from llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index) (0.6.54)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.6,>=0.5.0->llama-index) (1.9.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.6,>=0.5.0->llama-index) (0.11.1)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.6,>=0.5.0->llama-index) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<2.3.0->llama-index-readers-file<0.6,>=0.5.0->llama-index) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.3.0->llama-index-readers-file<0.6,>=0.5.0->llama-index) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<2.3.0->llama-index-readers-file<0.6,>=0.5.0->llama-index) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.7->llama-index) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.7->llama-index) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.7->llama-index) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->llama-index-core<0.15.0,>=0.14.7->llama-index) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->llama-index-core<0.15.0,>=0.14.7->llama-index) (2.5.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.49->sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15.0,>=0.14.7->llama-index) (3.2.4)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect>=0.8.0->llama-index-core<0.15.0,>=0.14.7->llama-index) (1.1.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json->llama-index-core<0.15.0,>=0.14.7->llama-index) (3.26.1)
Requirement already satisfied: python-dotenv<2,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from llama-cloud-services>=0.6.54->llama-parse>=0.5.0->llama-index-readers-llama-parse>=0.4.0->llama-index) (1.2.1)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.12/dist-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->llama-index-core<0.15.0,>=0.14.7->llama-index) (25.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<2.3.0->llama-index-readers-file<0.6,>=0.5.0->llama-index) (1.17.0)
Requirement already satisfied: colorama>=0.4 in /usr/local/lib/python3.12/dist-packages (from griffe->banks<3,>=2.2.0->llama-index-core<0.15.0,>=0.14.7->llama-index) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->banks<3,>=2.2.0->llama-index-core<0.15.0,>=0.14.7->llama-index) (3.0.3)
Requirement already satisfied: llama-index-embeddings-huggingface in /usr/local/lib/python3.12/dist-packages (0.6.1)
Requirement already satisfied: huggingface-hub>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (0.36.0)
Requirement already satisfied: llama-index-core<0.15,>=0.13.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-embeddings-huggingface) (0.14.7)
Requirement already satisfied: sentence-transformers>=2.6.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-embeddings-huggingface) (5.1.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.2.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.13.2)
Requirement already satisfied: aiosqlite in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.21.0)
Requirement already satisfied: banks<3,>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.2.0)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.2.18)
Requirement already satisfied: dirtyjson<2,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.0.8)
Requirement already satisfied: filetype<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.2.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.28.1)
Requirement already satisfied: llama-index-workflows!=2.9.0,<3,>=2 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.11.0)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (3.5)
Requirement already satisfied: nltk>3.8.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.0.2)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (11.3.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (4.5.0)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.11.10)
Requirement already satisfied: setuptools>=80.9.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (80.9.0)
Requirement already satisfied: sqlalchemy>=1.4.49 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (2.0.44)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (8.5.0)
Requirement already satisfied: tiktoken>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.12.0)
Requirement already satisfied: typing-inspect>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (0.9.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15,>=0.13.0->llama-index-embeddings-huggingface) (1.17.3)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (4.57.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.8.0+cu126)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.16.3)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
# Generates a 1D embedding vector of 384 dimensions
def get_llama_embedding(text):
    return Settings.embed_model.get_text_embedding(text)

In [ ]:
# Apply the embedding function row by row
training['llama_embedding'] = training['clean_text'].apply(get_llama_embedding)

In [ ]:
training.head(20)

training.to_csv('training_embed.csv', index=False)

from google.colab import files
files.download('training_embed.csv')

# **Embeddings on Validation Set**

In [ ]:
# BERT Embedding
valid['bert_embedding'] = valid['clean_text'].apply(get_bert_embedding)

In [ ]:
# FinancialBERT Embedding
valid['financialBERT_embedding'] = valid['clean_text'].apply(get_financialbert_embedding)

In [ ]:
# Llama 3.1 Embedding
valid['llama_embedding'] = valid['clean_text'].apply(get_llama_embedding)

In [ ]:
valid.head(20)

valid.to_csv('valid_embed.csv', index=False)

from google.colab import files
files.download('valid_embed.csv')

In [ ]:
import pandas as pd
import csv
[;l.]

combined.to_csv("original_twitter_embed.csv", index=False)

# Class Balancing For Training Dataset

In [ ]:
# Issue is that labels 2 has a much greater sample size (64.7% of dataset) compared to 1 (20%) and 0 (15%)
training["label"].value_counts(normalize=True)

Neutral class comprises of 64.7% of the dataset compared to Bearish (15%) and Bullish (20%)

In [ ]:
import pandas as pd

# Class balance the training dataset while leaving our test csv alone
training_embed = pd.read_csv("training_embed.csv")

df_class0 = training_embed[training_embed['label'] == 0]
df_class1 = training_embed[training_embed['label'] == 1]
df_class2 = training_embed[training_embed['label'] == 2]

# sample without replacement the dataframe that contains class 2 for only 2000
df_class2_resample = df_class2.sample(n=2000, replace=False, random_state=42)

# stich the rows back together
df_balanced = pd.concat([df_class0, df_class1, df_class2_resample], axis=0)
print(df_balanced['label'].value_counts())
print(training_embed['label'].value_counts())

df_balanced.to_csv('balanced_training_embed.csv', index=False)

label
2    2000
1    1923
0    1442
Name: count, dtype: int64
label
2    6178
1    1923
0    1442
Name: count, dtype: int64

The original training dataset had 6178 for Neutral, 1923 for Bullish, and 1442 for Bearish.

With the newly balanced training dataset, we have 2000 for Neutral, 1923 for Bullish, and 1442 for Bearish.